# Generated by Django 6.0 on 2025-12-15 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('code', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('purpose', models.CharField(choices=[('practice', 'Practice'), ('research', 'Research'), ('quality', 'Quality'), ('other', 'Other')], default='other', max_length=20)),
                ('is_longitudinal', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('development', 'Development'), ('production', 'Production'), ('inactive', 'Inactive')], default='development', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'proxmed_project',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-publish'], name='proxmed_pro_publish_0faade_idx')],
            },
        ),
    ]
