# Generated by Django 6.0 on 2025-12-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('projectform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_key', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='project.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'db_table': 'proxmed_records',
                'unique_together': {('project', 'record_key')},
            },
        ),
        migrations.CreateModel(
            name='FormStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('unverified', 'Unverified'), ('complete', 'Complete')], default='incomplete', max_length=12)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_statuses', to='project.event')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projectform.form')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_statuses', to='project.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_statuses', to='record.record')),
            ],
            options={
                'verbose_name': 'FormStatus',
                'verbose_name_plural': 'FormStatuses',
                'db_table': 'proxmed_form_status',
                'unique_together': {('project', 'record', 'event', 'form', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('instance', models.IntegerField(default=1)),
                ('value_long', models.TextField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_values', to='project.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_values', to='project.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_values', to='record.record')),
            ],
            options={
                'verbose_name': 'DataValue',
                'verbose_name_plural': 'DataValues',
                'db_table': 'proxmed_data_values',
                'indexes': [models.Index(fields=['project', 'field_name'], name='idx_field'), models.Index(fields=['project', 'record', 'event'], name='idx_record')],
                'unique_together': {('project', 'record', 'event', 'field_name', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='project.event')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='project.project')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='record.record')),
            ],
            options={
                'verbose_name': 'AuditLog',
                'verbose_name_plural': 'AuditLogs',
                'db_table': 'proxmed_audit_logs',
                'indexes': [models.Index(fields=['project', 'created_at'], name='idx_project_time')],
            },
        ),
    ]
