# Generated by Django 6.0 on 2025-12-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDVRule',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sdv_rule', serialize=False, to='project.project')),
                ('require_sdv_before_lock', models.BooleanField(default=False)),
                ('require_sdv_for_all_fields', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SDV Rule',
                'verbose_name_plural': 'SDV Rules',
                'db_table': 'proxmed_sdv_rules',
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=10)),
                ('scope', models.CharField(choices=[('field', 'Field'), ('form', 'Form'), ('event', 'Event'), ('record', 'Record')], max_length=10)),
                ('target_field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expression', models.TextField()),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_query_on_fail', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='project.project')),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'db_table': 'proxmed_validation_rules',
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance', models.IntegerField(default=1)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='active', max_length=10)),
                ('details_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.BigIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='project.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='project.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='record.record')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='datavalidation.validationrule')),
            ],
            options={
                'verbose_name': 'Validation Result',
                'verbose_name_plural': 'Validation Results',
                'db_table': 'proxmed_validation_results',
            },
        ),
        migrations.CreateModel(
            name='SDVFieldStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('instance', models.IntegerField(default=1)),
                ('sdv_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('verified', 'Verified'), ('not_verified', 'Not Verified')], default='pending', max_length=15)),
                ('verified_by', models.BigIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdv_field_statuses', to='project.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv_field_statuses', to='project.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv_field_statuses', to='record.record')),
            ],
            options={
                'verbose_name': 'SDV Field Status',
                'verbose_name_plural': 'SDV Field Statuses',
                'db_table': 'proxmed_sdv_field_status',
                'indexes': [models.Index(fields=['project', 'sdv_status'], name='idx_sdv')],
                'unique_together': {('project', 'record', 'event', 'field_name', 'instance')},
            },
        ),
        migrations.AddIndex(
            model_name='validationrule',
            index=models.Index(fields=['project', 'is_active'], name='idx_rule_active'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['project', 'status'], name='idx_val'),
        ),
    ]
