# Generated by Django 6.0 on 2025-12-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=255)),
                ('form_label', models.CharField(max_length=255)),
                ('form_order', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='project.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProjectForm',
                'verbose_name_plural': 'ProjectForms',
                'db_table': 'proxmed_project_forms',
                'ordering': ['form_order'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('field_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('notes', 'Notes'), ('calc', 'Calculated'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('yesno', 'Yes / No'), ('truefalse', 'True / False'), ('date', 'Date'), ('datetime', 'Date & Time'), ('file', 'File Upload'), ('slider', 'Slider')], max_length=16)),
                ('validation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('min_value', models.CharField(blank=True, max_length=50, null=True)),
                ('max_value', models.CharField(blank=True, max_length=50, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('branching_logic', models.TextField(blank=True, null=True)),
                ('calc_equation', models.TextField(blank=True, null=True)),
                ('field_order', models.IntegerField()),
                ('section_header', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='projectform.form')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='project.project')),
            ],
            options={
                'verbose_name': 'ProjectFormField',
                'verbose_name_plural': 'ProjectFormFields',
                'db_table': 'project_form_fields',
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('choice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coded_value', models.CharField(max_length=50)),
                ('label', models.TextField()),
                ('choice_order', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='projectform.formfield')),
            ],
            options={
                'verbose_name': 'FieldChoice',
                'verbose_name_plural': 'FieldChoices',
                'db_table': 'field_choices',
                'ordering': ['choice_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEventForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='project.event')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='projectform.form')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_forms', to='project.project')),
            ],
            options={
                'verbose_name': 'ProjectEventForm',
                'verbose_name_plural': 'ProjectForms',
                'db_table': 'project_event_forms',
            },
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['form_order'], name='proxmed_pro_form_or_3a0cee_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['field_order'], name='project_for_field_o_a03728_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('project', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='projecteventform',
            unique_together={('event', 'form')},
        ),
    ]
