# Generated by Django 6.0 on 2025-12-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='repeatingrule',
            name='event_or_form_not_both',
        ),
        migrations.DeleteModel(
            name='RepeatingRule',
        ),
    ]
