# Generated by Django 6.0 on 2025-12-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecteventform',
            options={'verbose_name': 'ProjectEventForm', 'verbose_name_plural': 'ProjectEventForms'},
        ),
    ]
