"""Add plan_features table

Revision ID: aad62e20d1d7
Revises: d22268930a1c
Create Date: 2025-12-09 22:39:37.796572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad62e20d1d7'
down_revision: Union[str, Sequence[str], None] = 'd22268930a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plan_features',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column('key_name', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key_name')
    )
    op.create_index(op.f('ix_plan_features_id'), 'plan_features', ['id'], unique=False)
    op.create_index(op.f('ix_plan_features_key_name'), 'plan_features', ['key_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_features_key_name'), table_name='plan_features')
    op.drop_index(op.f('ix_plan_features_id'), table_name='plan_features')
    op.drop_table('plan_features')
    # ### end Alembic commands ###
