 
import type Entity from '$lib/models/Entity';
export let CountryList: Entity[] = [
	{"name": "Afghanistan", "id": "AF", selected: false },
    {"name": "Åland Islands", "id": "AX", selected: false },
    {"name": "Albania", "id": "AL", selected: false },
    {"name": "Algeria", "id": "DZ", selected: false },
    {"name": "American Samoa", "id": "AS", selected: false },
    {"name": "AndorrA", "id": "AD", selected: false },
    {"name": "Angola", "id": "AO", selected: false },
    {"name": "Anguilla", "id": "AI", selected: false },
    {"name": "Antarctica", "id": "AQ", selected: false },
    {"name": "Antigua and Barbuda", "id": "AG", selected: false },
    {"name": "Argentina", "id": "AR", selected: false },
    {"name": "Armenia", "id": "AM", selected: false },
    {"name": "Aruba", "id": "AW", selected: false },
    {"name": "Australia", "id": "AU", selected: false },
    {"name": "Austria", "id": "AT", selected: false },
    {"name": "Azerbaijan", "id": "AZ", selected: false },
    {"name": "Bahamas", "id": "BS", selected: false },
    {"name": "Bahrain", "id": "BH", selected: false },
    {"name": "Bangladesh", "id": "BD", selected: false },
    {"name": "Barbados", "id": "BB", selected: false },
    {"name": "Belarus", "id": "BY", selected: false },
    {"name": "Belgium", "id": "BE", selected: false },
    {"name": "Belize", "id": "BZ", selected: false },
    {"name": "Benin", "id": "BJ", selected: false },
    {"name": "Bermuda", "id": "BM", selected: false },
    {"name": "Bhutan", "id": "BT", selected: false },
    {"name": "Bolivia", "id": "BO", selected: false },
    {"name": "Bosnia and Herzegovina", "id": "BA", selected: false },
    {"name": "Botswana", "id": "BW", selected: false },
    {"name": "Bouvet Island", "id": "BV", selected: false },
    {"name": "Brazil", "id": "BR", selected: false },
    {"name": "British Indian Ocean Territory", "id": "IO", selected: false },
    {"name": "Brunei Darussalam", "id": "BN", selected: false },
    {"name": "Bulgaria", "id": "BG", selected: false },
    {"name": "Burkina Faso", "id": "BF", selected: false },
    {"name": "Burundi", "id": "BI", selected: false },
    {"name": "Cambodia", "id": "KH", selected: false },
    {"name": "Cameroon", "id": "CM", selected: false },
    {"name": "Canada", "id": "CA", selected: false },
    {"name": "Cape Verde", "id": "CV", selected: false },
    {"name": "Cayman Islands", "id": "KY", selected: false },
    {"name": "Central African Republic", "id": "CF", selected: false },
    {"name": "Chad", "id": "TD", selected: false },
    {"name": "Chile", "id": "CL", selected: false },
    {"name": "China", "id": "CN", selected: false },
    {"name": "Christmas Island", "id": "CX", selected: false },
    {"name": "Cocos (Keeling) Islands", "id": "CC", selected: false },
    {"name": "Colombia", "id": "CO", selected: false },
    {"name": "Comoros", "id": "KM", selected: false },
    {"name": "Congo", "id": "CG", selected: false },
    {"name": "Congo, The Democratic Republic of the", "id": "CD", selected: false },
    {"name": "Cook Islands", "id": "CK", selected: false },
    {"name": "Costa Rica", "id": "CR", selected: false },
    {"name": "Cote D'Ivoire", "id": "CI", selected: false },
    {"name": "Croatia", "id": "HR", selected: false },
    {"name": "Cuba", "id": "CU", selected: false },
    {"name": "Cyprus", "id": "CY", selected: false },
    {"name": "Czech Republic", "id": "CZ", selected: false },
    {"name": "Denmark", "id": "DK", selected: false },
    {"name": "Djibouti", "id": "DJ", selected: false },
    {"name": "Dominica", "id": "DM", selected: false },
    {"name": "Dominican Republic", "id": "DO", selected: false },
    {"name": "Ecuador", "id": "EC", selected: false },
    {"name": "Egypt", "id": "EG", selected: false },
    {"name": "El Salvador", "id": "SV", selected: false },
    {"name": "Equatorial Guinea", "id": "GQ", selected: false },
    {"name": "Eritrea", "id": "ER", selected: false },
    {"name": "Estonia", "id": "EE", selected: false },
    {"name": "Ethiopia", "id": "ET", selected: false },
    {"name": "Falkland Islands (Malvinas)", "id": "FK", selected: false },
    {"name": "Faroe Islands", "id": "FO", selected: false },
    {"name": "Fiji", "id": "FJ", selected: false },
    {"name": "Finland", "id": "FI", selected: false },
    {"name": "France", "id": "FR", selected: false },
    {"name": "French Guiana", "id": "GF", selected: false },
    {"name": "French Polynesia", "id": "PF", selected: false },
    {"name": "French Southern Territories", "id": "TF", selected: false },
    {"name": "Gabon", "id": "GA", selected: false },
    {"name": "Gambia", "id": "GM", selected: false },
    {"name": "Georgia", "id": "GE", selected: false },
    {"name": "Germany", "id": "DE", selected: false },
    {"name": "Ghana", "id": "GH", selected: false },
    {"name": "Gibraltar", "id": "GI", selected: false },
    {"name": "Greece", "id": "GR", selected: false },
    {"name": "Greenland", "id": "GL", selected: false },
    {"name": "Grenada", "id": "GD", selected: false },
    {"name": "Guadeloupe", "id": "GP", selected: false },
    {"name": "Guam", "id": "GU", selected: false },
    {"name": "Guatemala", "id": "GT", selected: false },
    {"name": "Guernsey", "id": "GG", selected: false },
    {"name": "Guinea", "id": "GN", selected: false },
    {"name": "Guinea-Bissau", "id": "GW", selected: false },
    {"name": "Guyana", "id": "GY", selected: false },
    {"name": "Haiti", "id": "HT", selected: false },
    {"name": "Heard Island and Mcdonald Islands", "id": "HM", selected: false },
    {"name": "Holy See (Vatican City State)", "id": "VA", selected: false },
    {"name": "Honduras", "id": "HN", selected: false },
    {"name": "Hong Kong", "id": "HK", selected: false },
    {"name": "Hungary", "id": "HU", selected: false },
    {"name": "Iceland", "id": "IS", selected: false },
    {"name": "India", "id": "IN", selected: false },
    {"name": "Indonesia", "id": "ID", selected: false },
    {"name": "Iran, Islamic Republic Of", "id": "IR", selected: false },
    {"name": "Iraq", "id": "IQ", selected: false },
    {"name": "Ireland", "id": "IE", selected: false },
    {"name": "Isle of Man", "id": "IM", selected: false },
    {"name": "Italy", "id": "IT", selected: false },
    {"name": "Jamaica", "id": "JM", selected: false },
    {"name": "Japan", "id": "JP", selected: false },
    {"name": "Jersey", "id": "JE", selected: false },
    {"name": "Jordan", "id": "JO", selected: false },
    {"name": "Kazakhstan", "id": "KZ", selected: false },
    {"name": "Kenya", "id": "KE", selected: false },
    {"name": "Kiribati", "id": "KI", selected: false },
    {"name": "Korea, Democratic People'S Republic of", "id": "KP", selected: false },
    {"name": "Korea, Republic of", "id": "KR", selected: false },
    {"name": "Kuwait", "id": "KW", selected: false },
    {"name": "Kyrgyzstan", "id": "KG", selected: false },
    {"name": "Lao People'S Democratic Republic", "id": "LA", selected: false },
    {"name": "Latvia", "id": "LV", selected: false },
    {"name": "Lebanon", "id": "LB", selected: false },
    {"name": "Lesotho", "id": "LS", selected: false },
    {"name": "Liberia", "id": "LR", selected: false },
    {"name": "Libyan Arab Jamahiriya", "id": "LY", selected: false },
    {"name": "Liechtenstein", "id": "LI", selected: false },
    {"name": "Lithuania", "id": "LT", selected: false },
    {"name": "Luxembourg", "id": "LU", selected: false },
    {"name": "Macao", "id": "MO", selected: false },
    {"name": "Macedonia, The Former Yugoslav Republic of", "id": "MK", selected: false },
    {"name": "Madagascar", "id": "MG", selected: false },
    {"name": "Malawi", "id": "MW", selected: false },
    {"name": "Malaysia", "id": "MY", selected: false },
    {"name": "Maldives", "id": "MV", selected: false },
    {"name": "Mali", "id": "ML", selected: false },
    {"name": "Malta", "id": "MT", selected: false },
    {"name": "Marshall Islands", "id": "MH", selected: false },
    {"name": "Martinique", "id": "MQ", selected: false },
    {"name": "Mauritania", "id": "MR", selected: false },
    {"name": "Mauritius", "id": "MU", selected: false },
    {"name": "Mayotte", "id": "YT", selected: false },
    {"name": "Mexico", "id": "MX", selected: false },
    {"name": "Micronesia, Federated States of", "id": "FM", selected: false },
    {"name": "Moldova, Republic of", "id": "MD", selected: false },
    {"name": "Monaco", "id": "MC", selected: false },
    {"name": "Mongolia", "id": "MN", selected: false },
    {"name": "Montserrat", "id": "MS", selected: false },
    {"name": "Morocco", "id": "MA", selected: false },
    {"name": "Mozambique", "id": "MZ", selected: false },
    {"name": "Myanmar", "id": "MM", selected: false },
    {"name": "Namibia", "id": "NA", selected: false },
    {"name": "Nauru", "id": "NR", selected: false },
    {"name": "Nepal", "id": "NP", selected: false },
    {"name": "Netherlands", "id": "NL", selected: false },
    {"name": "Netherlands Antilles", "id": "AN", selected: false },
    {"name": "New Caledonia", "id": "NC", selected: false },
    {"name": "New Zealand", "id": "NZ", selected: false },
    {"name": "Nicaragua", "id": "NI", selected: false },
    {"name": "Niger", "id": "NE", selected: false },
    {"name": "Nigeria", "id": "NG", selected: false },
    {"name": "Niue", "id": "NU", selected: false },
    {"name": "Norfolk Island", "id": "NF", selected: false },
    {"name": "Northern Mariana Islands", "id": "MP", selected: false },
    {"name": "Norway", "id": "NO", selected: false },
    {"name": "Oman", "id": "OM", selected: false },
    {"name": "Pakistan", "id": "PK", selected: false },
    {"name": "Palau", "id": "PW", selected: false },
    {"name": "Palestinian Territory, Occupied", "id": "PS", selected: false },
    {"name": "Panama", "id": "PA", selected: false },
    {"name": "Papua New Guinea", "id": "PG", selected: false },
    {"name": "Paraguay", "id": "PY", selected: false },
    {"name": "Peru", "id": "PE", selected: false },
    {"name": "Philippines", "id": "PH", selected: false },
    {"name": "Pitcairn", "id": "PN", selected: false },
    {"name": "Poland", "id": "PL", selected: false },
    {"name": "Portugal", "id": "PT", selected: false },
    {"name": "Puerto Rico", "id": "PR", selected: false },
    {"name": "Qatar", "id": "QA", selected: false },
    {"name": "Reunion", "id": "RE", selected: false },
    {"name": "Romania", "id": "RO", selected: false },
    {"name": "Russian Federation", "id": "RU", selected: false },
    {"name": "RWANDA", "id": "RW", selected: false },
    {"name": "Saint Helena", "id": "SH", selected: false },
    {"name": "Saint Kitts and Nevis", "id": "KN", selected: false },
    {"name": "Saint Lucia", "id": "LC", selected: false },
    {"name": "Saint Pierre and Miquelon", "id": "PM", selected: false },
    {"name": "Saint Vincent and the Grenadines", "id": "VC", selected: false },
    {"name": "Samoa", "id": "WS", selected: false },
    {"name": "San Marino", "id": "SM", selected: false },
    {"name": "Sao Tome and Principe", "id": "ST", selected: false },
    {"name": "Saudi Arabia", "id": "SA", selected: false },
    {"name": "Senegal", "id": "SN", selected: false },
    {"name": "Serbia and Montenegro", "id": "CS", selected: false },
    {"name": "Seychelles", "id": "SC", selected: false },
    {"name": "Sierra Leone", "id": "SL", selected: false },
    {"name": "Singapore", "id": "SG", selected: false },
    {"name": "Slovakia", "id": "SK", selected: false },
    {"name": "Slovenia", "id": "SI", selected: false },
    {"name": "Solomon Islands", "id": "SB", selected: false },
    {"name": "Somalia", "id": "SO", selected: false },
    {"name": "South Africa", "id": "ZA", selected: false },
    {"name": "South Georgia and the South Sandwich Islands", "id": "GS", selected: false },
    {"name": "Spain", "id": "ES", selected: false },
    {"name": "Sri Lanka", "id": "LK", selected: false },
    {"name": "Sudan", "id": "SD", selected: false },
    {"name": "Suriname", "id": "SR", selected: false },
    {"name": "Svalbard and Jan Mayen", "id": "SJ", selected: false },
    {"name": "Swaziland", "id": "SZ", selected: false },
    {"name": "Sweden", "id": "SE", selected: false },
    {"name": "Switzerland", "id": "CH", selected: false },
    {"name": "Syrian Arab Republic", "id": "SY", selected: false },
    {"name": "Taiwan, Province of China", "id": "TW", selected: false },
    {"name": "Tajikistan", "id": "TJ", selected: false },
    {"name": "Tanzania, United Republic of", "id": "TZ", selected: false },
    {"name": "Thailand", "id": "TH", selected: false },
    {"name": "Timor-Leste", "id": "TL", selected: false },
    {"name": "Togo", "id": "TG", selected: false },
    {"name": "Tokelau", "id": "TK", selected: false },
    {"name": "Tonga", "id": "TO", selected: false },
    {"name": "Trinidad and Tobago", "id": "TT", selected: false },
    {"name": "Tunisia", "id": "TN", selected: false },
    {"name": "Turkey", "id": "TR", selected: false },
    {"name": "Turkmenistan", "id": "TM", selected: false },
    {"name": "Turks and Caicos Islands", "id": "TC", selected: false },
    {"name": "Tuvalu", "id": "TV", selected: false },
    {"name": "Uganda", "id": "UG", selected: false },
    {"name": "Ukraine", "id": "UA", selected: false },
    {"name": "United Arab Emirates", "id": "AE", selected: false },
    {"name": "United Kingdom", "id": "GB", selected: false },
    {"name": "United States", "id": "US", selected: true },
    {"name": "United States Minor Outlying Islands", "id": "UM", selected: false },
    {"name": "Uruguay", "id": "UY", selected: false },
    {"name": "Uzbekistan", "id": "UZ", selected: false },
    {"name": "Vanuatu", "id": "VU", selected: false },
    {"name": "Venezuela", "id": "VE", selected: false },
    {"name": "Viet Nam", "id": "VN", selected: false },
    {"name": "Virgin Islands, British", "id": "VG", selected: false },
    {"name": "Virgin Islands, U.S.", "id": "VI", selected: false },
    {"name": "Wallis and Futuna", "id": "WF", selected: false },
    {"name": "Western Sahara", "id": "EH", selected: false },
    {"name": "Yemen", "id": "YE", selected: false },
    {"name": "Zambia", "id": "ZM", selected: false },
    {"name": "Zimbabwe", "id": "ZW"} 

]; 
export let MonthList: Entity[] = [
	{ id: '01', name: 'January' , selected: false},
	{ id: '02', name: 'February' , selected: false}, 
    { id: '03', name: 'March' , selected: false},  
    { id: '04', name: 'April' , selected: false}, 
    { id: '05', name: 'May' , selected: false}, 
    { id: '06', name: 'June' , selected: false}, 
    { id: '07', name: 'July' , selected: false}, 
    { id: '08', name: 'August' , selected: false}, 
    { id: '09', name: 'September' , selected: false}, 
    { id: '10', name: 'October' , selected: false}, 
    { id: '11', name: 'November' , selected: false}, 
    { id: '12', name: 'December' , selected: false}, 

]; 
 