# Generated by Django 6.0 on 2025-12-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('projectform', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuery',
            fields=[
                ('query_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('instance', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('raised_by', models.BigIntegerField()),
                ('assigned_to', models.BigIntegerField(blank=True, null=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_queries', to='project.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_queries', to='project.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_queries', to='record.record')),
            ],
            options={
                'verbose_name': 'DataQuery',
                'verbose_name_plural': 'DataQueries',
                'db_table': 'proxmed_data_queries',
            },
        ),
        migrations.CreateModel(
            name='DataQueryMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='compliance.dataquery')),
            ],
            options={
                'verbose_name': 'DataQueryMessage',
                'verbose_name_plural': 'DataQueryMessages',
                'db_table': 'proxmed_data_query_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldReviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('instance', models.IntegerField(default=1)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('needs_review', 'Needs Review')], default='unreviewed', max_length=15)),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='project.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='project.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='record.record')),
            ],
            options={
                'verbose_name': 'FieldReviewStatus',
                'verbose_name_plural': 'FieldReviewStatuses',
                'db_table': 'proxmed_field_review_status',
            },
        ),
        migrations.CreateModel(
            name='FormLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.IntegerField(default=1)),
                ('locked_by', models.BigIntegerField()),
                ('locked_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_locks', to='project.event')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='projectform.form')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_locks', to='project.project')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_locks', to='record.record')),
            ],
            options={
                'verbose_name': 'FormLock',
                'verbose_name_plural': 'FormLocks',
                'db_table': 'proxmed_form_locks',
            },
        ),
        migrations.CreateModel(
            name='QueryRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('block_form_completion', models.BooleanField(default=False)),
                ('auto_close_on_change', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_rules', to='project.project')),
            ],
            options={
                'verbose_name': 'QueryRule',
                'verbose_name_plural': 'QueryRules',
                'db_table': 'proxmed_query_rules',
            },
        ),
        migrations.CreateModel(
            name='SignatureMeaning',
            fields=[
                ('meaning_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_meanings', to='project.project')),
            ],
            options={
                'verbose_name': 'SignatureMeaning',
                'verbose_name_plural': 'SignatureMeanings',
                'db_table': 'proxmed_signature_meanings',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('signature_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField()),
                ('entity_type', models.CharField(choices=[('record', 'Record'), ('form', 'Form'), ('event', 'Event'), ('query', 'Query'), ('export', 'Export')], max_length=10)),
                ('instance', models.IntegerField(default=1)),
                ('signed_hash', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signer_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('signer_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('otp', 'OTP'), ('sso', 'SSO')], default='password', max_length=10)),
                ('auth_proof_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='project.event')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='projectform.form')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='project.project')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='compliance.dataquery')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='record.record')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='compliance.signaturemeaning')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'db_table': 'proxmed_signatures',
            },
        ),
        migrations.AddIndex(
            model_name='dataquery',
            index=models.Index(fields=['project', 'status'], name='idx_query_status'),
        ),
        migrations.AddIndex(
            model_name='fieldreviewstatus',
            index=models.Index(fields=['project', 'review_status'], name='idx_review'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldreviewstatus',
            unique_together={('project', 'record', 'event', 'field_name', 'instance')},
        ),
        migrations.AlterUniqueTogether(
            name='formlock',
            unique_together={('project', 'record', 'event', 'form', 'instance')},
        ),
        migrations.AlterUniqueTogether(
            name='signaturemeaning',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['project', 'entity_type', 'record', 'event', 'form', 'instance'], name='idx_sig_lookup'),
        ),
    ]
